name: Chi Trung Nguyen

#url: "[http://www.napcaesmind.de]"
host: 0.0.0.0

#markdown: redcarpet
markdown: kramdown
highligther: pygments

exlude: [status.php]

plugins: [jekyll-paginate]
paginate: 5
paginate_path: /blog/page:num/

