name: Chi Trung Nguyen

#url: "[http://www.napcaesmind.de]"

markdown: redcarpet
highligther: pygments

exlude: [status.php]
include: [.well-known]

gems: [jekyll-paginate]
paginate: 5
paginate_path: /blog/page:num/

